import { 
    faCartShopping,
    faTrashCan,
    faAdd,
    faSubtract,
    faCalendar,
    faTruckFast,
    faGlasses,
    faUser,
    faMoneyCheck,
    faListUl,
    faEnvelope,
    faPhone,
    faClock,
    faCalendarXmark,
    faPen,
    faGear,
    faIdCard,
    faPerson,
    faStore,
    faBusinessTime,
    faSquareCheck,
    faLocationDot,
    faBrush,
    faImage,
    faCamera,
    faHome,
    faEye,
    faCalendarPlus,
    faRightToBracket,
    faUserPlus,
    faUserLock,
    faXmark,
    faMagnifyingGlass,
    faChartLine,
    faCoins,
    faWarehouse,
    faCircleChevronLeft,
    faCircleChevronRight,
    faInfo,
    faSun,
    faMoon,
    faSliders,
    faPalette
 } from '@fortawesome/free-solid-svg-icons';

export const icons = {
    cart:  faCartShopping,
    trash: faTrashCan,
    add: faAdd,
    subtract: faSubtract,
    calendar: faCalendar,
    xCalendar: faCalendarXmark,
    plusCalendar: faCalendarPlus,
    truck: faTruckFast,
    glasses: faGlasses,
    user: faUser,
    money: faMoneyCheck,
    list: faListUl,
    envelope: faEnvelope,
    phone: faPhone,
    clock: faClock,
    pen: faPen,
    gear: faGear,
    id: faIdCard,
    person: faPerson,
    store: faStore,
    pending: faBusinessTime,
    ready: faStore,
    deliverd: faSquareCheck,
    canceled: faXmark,
    location: faLocationDot,
    paint: faBrush,
    image: faImage,
    camera: faCamera,
    home: faHome,
    eye: faEye,
    right: faRightToBracket,
    userPlus: faUserPlus,
    userLock: faUserLock,
    xmark: faXmark,
    search: faMagnifyingGlass,
    stats: faChartLine,
    coins: faCoins,
    box: faWarehouse,
    leftCircle: faCircleChevronLeft,
    rightCircle: faCircleChevronRight,
    info: faInfo,
    light: faSun,
    dark: faMoon,
    custom: faPalette,
    sliders: faSliders
};