export const translate = {
    confirm_changes_message: "Are you sure you want to apply these changes?",
    something_went_wrong: "Something went wrong!",
    action_success: "Action completed successfully!",
    passwords_dont_match: "Passwords don't match!",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    approve: "Approve",
    gallery: "Gallery",
    camera: "Camera",
    select_date: "Select Date",

    // Login
    id_placeholder: "ID",
    email_placeholder: "Email",
    name_placeholder: "Full Name",
    password_placeholder: "Password",
    are_you_an_employee: "Are you an Employee? ",
    forgot_password: "Forgot Password",
    dont_have_an_account: "Don't have an account?",
    login: "Login",

    // Signup
    verify_password_placeholder: "Verify Password",
    phone_number_placeholder: "Phone Number: ex. 050-1234567",
    pick_date_of_birth: "Date Of Birth",
    already_signed: "Already Signed?",
    signup: "Sign-Up",

    // Forgot Password
    send_email_button: "Send Email",
    reset_password: "Reset Password",
    new_password_placeholder: "New Password",
    verify_new_password_placeholder: "Verify New Password",
    pincode_placeholder: "Pincode",

    // Home Page
    welcome_back: "Welcome Back!",
    appointment_card_title: "Next Appointments",
    appointment_button_title: "Booking >>",
    appoinments_settings_title: "Settings >>",
    shopping_card_title: "Shopping Cart",
    shopping_button_title: "Store >>",
    shopping_cart_button_title: "Shopping Cart >>",
    orders_card_title: "Orders",
    orders_button_title: "Orders >>",
    logout_button_title: "Log-Out",
    remove_appointment_message: "Do you want to remove this appointment?",

    // Appointments
    confirm_booking_message: "Do you want to confirm this booking?",
    time_placeholder: "Time",
    create: "Create",
    start_hour_placeholder: "Start Hour",
    start_minute_placeholder: "Start Minute",
    end_hour_placeholder: "End Hour",
    end_minute_placeholder: "End Minute",
    select_appointment_type: "Select Appointment Type",
    type_placeholder: "Type",
    missing_appointment_type: "Please select an appointment type",
    remove_appointment_type_message: "Do you want to remove this appointment type?",
    remove_day_off_message: "Do you want to remove this day off?",
    remove_avaliable_block_message: "Do you want to remove this working block?",
    edit_slot_duration_message: "Do you want to edit slot duration?",
    edit_appointment_type_message: "Do you want to edit this appointment type?",
    booked: "Booked",
    available: "Available",

    // Appointments Settings
    appoinments_types_title: "Appointments Types",
    days_off_title: "Days Off",
    working_hours_title: "Working Hours",
    appoinments_duration_title: "Appointments Duration",
    start_time_placeholder: "Start Time: ",
    end_time_placeholder: "End Time: ",
    day_of_week_placeholder: "Day of Week",
    date_placeholder: "Date: ",
    hours_placeholder: "Hours: ",
    minutes_placeholder: "Minutes: ",
    add_custom_slot: "Add Custom Slot",
    add_appointment_type_title: "Create A New Appointment Type",
    add_day_off_title: "Add A New Day Off",
    add_working_hours_title: "Add A New Working Hours Block",
    add_custom_slot_title: "Add A New Custom Appointment Slot",
    select_day: "Select Day",
    
    // Store
    add_to_cart: "Add To Cart",
    buy_now: "Buy Now! Total: ",
    edit: "Edit",
    name_placeholder: "Name",
    description_placeholder: "Description",
    price_placeholder: "Price",
    stock_placeholder: "Stock",
    quantity_placeholder: "Quantity",
    submit_button: "Submit",
    remove_confirm_message: "Are you sure you want to remove this product?",
    order_confirm_message: "Please confirm your order",
    order_success_message: "Your order has been placed successfully!",
    order_fail_message: "Your order has failed to be placed",
    phone_placeholder: "Phone Number",
    total_price: "Total Price",
    set_order_pending: "Set Pending",
    set_order_ready: "Set Ready",
    set_order_delivered: "Set Delivered",
    upload_image: "Upload Image",
    edit_product_title: "Edit Product",
    add_product_title: "Add Product",
    chage_status_message: "Do you want to change this order status?",
    item_already_in_cart: "Item is already in cart!",
    continue_shopping: "Continue Shopping",
    go_to_cart: "Go To Cart",
    income_per_month: "Income Per Month",
    item_added_to_cart: "Item has been added to cart!",
    you_refused_to_allow_this_app_to_access_your_camera : "You've refused to allow this app to access your camera! :(",

    // Statistics
    select_dates: "Select Dates",
    product_units_sold: "Number Of Units Sold",
    product_total_income: "Income Per Product",
    orders_amount: "Number Of Orders",
    orders_income: "Monthly Orders Income",
    note_next_month_is_a_prediction: "Note! Next month value is a prediction based on your previous sales!",
    pending_orders: "Pending Orders",
    ready_orders: "Ready Orders",
    delivered_orders: "Delivered Orders",
    canceled_orders: "Canceled Orders",
    products_sold: "Products Sold",
    general_card_title: "General Information",

    // Settings
    theme_card_title: "Theme",
    dark: "Dark",
    light: "Light",
    custom: "Custom",
    user_card_title: "User",
    id_label: "ID: ",
    name_label: "Name: ",
    email_label: "Email: ",
    phone_label: "Phone Number: ",
    date_of_birth_label: "Date of Birth: ",
    address_label: "Address: ",
    tenant_card_title: "Shop",
    background_color: "Background Color",
    buttons_color: "Buttons Color",
    icons_color: "Icons Color",
    save_changes: "Save Changes",
    cancel: "Cancel",
    customize_colors: "Customize Colors",

    // Sight Test
    distance_instruction: "Keep your phone in arm length distance, cover your right eye and click start test when you are ready.",
    cover_your_eye_instruction: (eye) => `Please cover your ${eye} eye.`,
    select_correct_circle : "Select the circle that is showen above:",
    cant_see: "I can't see",
    switch_eyes_message: "Good job! Let\'s switch eyes!",
    completed_test_message: "Good job! You have completed the test!",
    start_test: "Start Test!",
    you_will_be_shown_a_circle: "You will be shown a circle with a fraction on it.",
    you_will_select_the_corrcet_circle: "You will be asked to select the circle that is described above from 3 options.",
    you_can_click_i_cant_see: "You can always click the \"I can't see\" button if you can't see the correct answer.",
    note_timed_test: "Note that the test takes your reaction time into account, so please answer as fast as you can.",
    left_eye_result: "Left Eye Results",
    right_eye_result: "Right Eye Results",
    you_have_perfect_vision: "You have perfect vision!",
    you_have_almost_perfect_vision: "You have almost perfect vision!",
    might_be_recommended_to_come_by_for_a_checkup: "It might be recommended to come by for a checkup.",
    it_is_recommended_to_come_by_for_a_checkup: "It is recommended to come by for a checkup.",
    you_should_use_glasses_please_come_by_for_a_checkup: "Results are not so good, you are adviced to come by for a checkup.",
    You_defently_should_use_glasses_please_come_by_for_a_checkup: "Results are not good, you are strongly adviced to come by for a checkup.",
    welcome_to_our_online_sight_test: "Welcome to our online sight test!",
    eye_score: "Eye Score: ",
    try_again: "Try Test Again",
}