image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet restore ./OMSAPI
          - dotnet build ./OMSAPI
          - dotnet test ./OMSAPITesting